NINAPRO_DB5_EX_A_LABEL_TO_GESTURE = {
    0: "Rest",
    1: "Index flexion",
    2: "Index extension",
    3: "Middle flexion",
    4: "Middle extension",
    5: "Ring flexion",
    6: "Ring extension",
    7: "Little finger flexion",
    8: "Little finger extension",
    9: "Thumb adduction",
    10: "Thumb abduction",
    11: "Thumb flexion",
    12: "Thumb extension"
}

NINAPRO_DB5_EX_A_GESTURE_TO_LABEL = {
    "Rest": 0,
    "Index flexion": 1,
    "Index extension": 2,
    "Middle flexion": 3,
    "Middle extension": 4,
    "Ring flexion": 5,
    "Ring extension": 6,
    "Little finger flexion": 7,
    "Little finger extension": 8,
    "Thumb adduction": 9,
    "Thumb abduction": 10,
    "Thumb flexion": 11,
    "Thumb extension": 12
}

NINAPRO_DB5_EX_B_LABEL_TO_GESTURE = {
    0: "Rest",
    1: "Thumb up",
    2: "Extension of index and middle, flexion of the others",
    3: "Flexion of ring and little finger, extension of the others",
    4: "Thumb opposing base of little finger",
    5: "Abduction of all fingers",
    6: "Fingers flexed together in fist",
    7: "Pointing index",
    8: "Adduction of extended fingers",
    9: "Wrist supination (axis: middle finger)",
    10: "Wrist pronation (axis: middle finger)",
    11: "Wrist supination (axis: little finger)",
    12: "Wrist pronation (axis: little finger)",
    13: "Wrist flexion",
    14: "Wrist extension",
    15: "Wrist radial deviation",
    16: "Wrist ulnar deviation",
    17: "Wrist extension with closed hand"
}

NINAPRO_DB5_EX_B_GESTURE_TO_LABEL = {
    "Rest": 0,
    "Thumb up": 1,
    "Extension of index and middle, flexion of the others": 2,
    "Flexion of ring and little finger, extension of the others": 3,
    "Thumb opposing base of little finger": 4,
    "Abduction of all fingers": 5,
    "Fingers flexed together in fist": 6,
    "Pointing index": 7,
    "Adduction of extended fingers": 8,
    "Wrist supination (axis: middle finger)": 9,
    "Wrist pronation (axis: middle finger)": 10,
    "Wrist supination (axis: little finger)": 11,
    "Wrist pronation (axis: little finger)": 12,
    "Wrist flexion": 13,
    "Wrist extension": 14,
    "Wrist radial deviation": 15,
    "Wrist ulnar deviation": 16,
    "Wrist extension with closed hand": 17
}

NINAPRO_DB5_EX_C_LABEL_TO_GESTURE = {
    0: "Rest",
    1: "Large diameter grasp",
    2: "Small diameter grasp (power grip)",
    3: "Fixed hook grasp",
    4: "Index finger extension grasp",
    5: "Medium wrap",
    6: "Ring grasp",
    7: "Prismatic four fingers grasp",
    8: "Stick grasp",
    9: "Writing tripod grasp",
    10: "Power sphere grasp",
    11: "Three finger sphere grasp",
    12: "Precision sphere grasp",
    13: "Tripod grasp",
    14: "Prismatic pinch grasp",
    15: "Tip pinch grasp",
    16: "Quadpod grasp",
    17: "Lateral grasp",
    18: "Parallel extension grasp",
    19: "Extension type grasp",
    20: "Power disk grasp",
    21: "Open a bottle with a tripod grasp",
    22: "Turn a screw (grasp the screwdriver with a stick grasp)",
    23: "Cut something (grasp the knife with an index finger extension grasp)"
}

NINAPRO_DB5_EX_C_GESTURE_TO_LABEL = {
    "Rest": 0,
    "Large diameter grasp": 1,
    "Small diameter grasp (power grip)": 2,
    "Fixed hook grasp": 3,
    "Index finger extension grasp": 4,
    "Medium wrap": 5,
    "Ring grasp": 6,
    "Prismatic four fingers grasp": 7,
    "Stick grasp": 8,
    "Writing tripod grasp": 9,
    "Power sphere grasp": 10,
    "Three finger sphere grasp": 11,
    "Precision sphere grasp": 12,
    "Tripod grasp": 13,
    "Prismatic pinch grasp": 14,
    "Tip pinch grasp": 15,
    "Quadpod grasp": 16,
    "Lateral grasp": 17,
    "Parallel extension grasp": 18,
    "Extension type grasp": 19,
    "Power disk grasp": 20,
    "Open a bottle with a tripod grasp": 21,
    "Turn a screw (grasp the screwdriver with a stick grasp)": 22,
    "Cut something (grasp the knife with an index finger extension grasp)": 23
}

NINAPRO_DB5_ALL_LABEL_TO_GESTURE = {
    0: "Rest",
    1: "Index flexion",
    2: "Index extension",
    3: "Middle flexion",
    4: "Middle extension",
    5: "Ring flexion",
    6: "Ring extension",
    7: "Little finger flexion",
    8: "Little finger extension",
    9: "Thumb adduction",
    10: "Thumb abduction",
    11: "Thumb flexion",
    12: "Thumb extension",
    13: "Thumb up",
    14: "Extension of index and middle, flexion of the others",
    15: "Flexion of ring and little finger, extension of the others",
    16: "Thumb opposing base of little finger",
    17: "Abduction of all fingers",
    18: "Fingers flexed together in fist",
    19: "Pointing index",
    20: "Adduction of extended fingers",
    21: "Wrist supination (axis: middle finger)",
    22: "Wrist pronation (axis: middle finger)",
    23: "Wrist supination (axis: little finger)",
    24: "Wrist pronation (axis: little finger)",
    25: "Wrist flexion",
    26: "Wrist extension",
    27: "Wrist radial deviation",
    28: "Wrist ulnar deviation",
    29: "Wrist extension with closed hand",
    30: "Large diameter grasp",
    31: "Small diameter grasp (power grip)",
    32: "Fixed hook grasp",
    33: "Index finger extension grasp",
    34: "Medium wrap",
    35: "Ring grasp",
    36: "Prismatic four fingers grasp",
    37: "Stick grasp",
    38: "Writing tripod grasp",
    39: "Power sphere grasp",
    40: "Three finger sphere grasp",
    41: "Precision sphere grasp",
    42: "Tripod grasp",
    43: "Prismatic pinch grasp",
    44: "Tip pinch grasp",
    45: "Quadpod grasp",
    46: "Lateral grasp",
    47: "Parallel extension grasp",
    48: "Extension type grasp",
    49: "Power disk grasp",
    50: "Open a bottle with a tripod grasp",
    51: "Turn a screw (grasp the screwdriver with a stick grasp)",
    52: "Cut something (grasp the knife with an index finger extension grasp)"
}

NINAPRO_DB5_ALL_GESTURE_TO_LABEL = {
    "Rest": 0,
    "Index flexion": 1,
    "Index extension": 2,
    "Middle flexion": 3,
    "Middle extension": 4,
    "Ring flexion": 5,
    "Ring extension": 6,
    "Little finger flexion": 7,
    "Little finger extension": 8,
    "Thumb adduction": 9,
    "Thumb abduction": 10,
    "Thumb flexion": 11,
    "Thumb extension": 12,
    "Thumb up": 13,
    "Extension of index and middle, flexion of the others": 14,
    "Flexion of ring and little finger, extension of the others": 15,
    "Thumb opposing base of little finger": 16,
    "Abduction of all fingers": 17,
    "Fingers flexed together in fist": 18,
    "Pointing index": 19,
    "Adduction of extended fingers": 20,
    "Wrist supination (axis: middle finger)": 21,
    "Wrist pronation (axis: middle finger)": 22,
    "Wrist supination (axis: little finger)": 23,
    "Wrist pronation (axis: little finger)": 24,
    "Wrist flexion": 25,
    "Wrist extension": 26,
    "Wrist radial deviation": 27,
    "Wrist ulnar deviation": 28,
    "Wrist extension with closed hand": 29,
    "Large diameter grasp": 30,
    "Small diameter grasp (power grip)": 31,
    "Fixed hook grasp": 32,
    "Index finger extension grasp": 33,
    "Medium wrap": 34,
    "Ring grasp": 35,
    "Prismatic four fingers grasp": 36,
    "Stick grasp": 37,
    "Writing tripod grasp": 38,
    "Power sphere grasp": 39,
    "Three finger sphere grasp": 40,
    "Precision sphere grasp": 41,
    "Tripod grasp": 42,
    "Prismatic pinch grasp": 43,
    "Tip pinch grasp": 44,
    "Quadpod grasp": 45,
    "Lateral grasp": 46,
    "Parallel extension grasp": 47,
    "Extension type grasp": 48,
    "Power disk grasp": 49,
    "Open a bottle with a tripod grasp": 50,
    "Turn a screw (grasp the screwdriver with a stick grasp)": 51,
    "Cut something (grasp the knife with an index finger extension grasp)": 52
}

EXP_TO_GESTURES_LIST = {
    "all": list(NINAPRO_DB5_ALL_GESTURE_TO_LABEL.keys())[1:],
    "ex_a": list(NINAPRO_DB5_EX_A_GESTURE_TO_LABEL.keys())[1:],
    "ex_b": list(NINAPRO_DB5_EX_B_GESTURE_TO_LABEL.keys())[1:],
    "ex_c": list(NINAPRO_DB5_EX_C_GESTURE_TO_LABEL.keys())[1:],
    "ex_ab": list(NINAPRO_DB5_EX_A_GESTURE_TO_LABEL.keys())[1:] + list(NINAPRO_DB5_EX_B_GESTURE_TO_LABEL.keys())[1:],
    "ex_bc": list(NINAPRO_DB5_EX_B_GESTURE_TO_LABEL.keys())[1:] + list(NINAPRO_DB5_EX_C_GESTURE_TO_LABEL.keys())[1:],
    "ex_ac": list(NINAPRO_DB5_EX_A_GESTURE_TO_LABEL.keys())[1:] + list(NINAPRO_DB5_EX_C_GESTURE_TO_LABEL.keys())[1:],
}